version: '3.3'

services:
  react-app:
    build: 
      context: frontend/tonbite.client
    ports:
       - "5173:80"
    depends_on:
       - api 


  api: 
    build:
      context: backend/Tonbite.Api
    ports:
       - "7085:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
       - db 

  db:
   image: postgres:13
   environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: tonbite
     POSTGRES_USER_ID: postgres
   ports:
    - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
